#markdown: rdiscount
# 2020年02月08日 修改，为了TOC
markdown: kramdown
permalink: /:title/
url: http://huangli.github.io
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
paginate: 30
paginate_path: "page:num"
name: 一路向东
description: 一路向东 | There are no limitations, except the ones you make
author: 黄立
email: ekinasm@gmail.com
hub: huangli
safe: false
about: "一路向东"
