# Site settings
title: 退居三线
email: ekinasm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  虽然从上海回到老家，不变的是依然喜欢写写程序，数据分析，依然要不断学习和成长。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://huangli.github.io/" # the base hostname & protocol for your site
twitter_username: huangli
github_username:  huangli

# Build settings
markdown: kramdown
